### ISSUE TITLE
Cannot open jupyter notebook in browser

### ISSUE THREAD

**Issue by FENGZHENGHFUT** [gilestrolab/ethoscopy#2]
HI,ggilestro
      I recently installed docker according to the manual's instructions.
sudo docker run -d -p 8080:8080 \
      --name ethoscope-lab \
      --volume /ethoscope_data/results:/mnt/ethoscope_results:ro \
      --volume /home:/mnt/my_user_homes \
      --restart=unless-stopped \
      ggilestro/ethoscope-lab

and 
sudo docker exec -it ethoscope-lab /bin/bash

then i open the http://0.0.0.0:8080 in my brower ， it demonstrate like:
the page located at "0.0.0.0" cannot be found.check the web address for misspelled words and try again. error receiving data: connection reset by peer.
http://localhost:8080 also didnot work.
 I don't know how to solve this problem.
thanks,Any help would be greatly appreciated

**Comment by ggilestro** [comment]
"Connection reset by peers" indicates that the container should be running but something is stuck. Try restarting the container with

`sudo docker restart ethoscope-lab`

or even restarting the computer. 

If that still does not work, please post here the logs:

`sudo docker logs ethoscope-lab`

**Comment by FENGZHENGHFUT** [comment]
Thanks for your response
 I had restarted the docker and computer ,but it didn't work.
the logs as follows：
![IMG_20230719_162604](https://github.com/gilestrolab/ethoscopy/assets/139935090/b23494fc-ad51-4763-9019-9c9638319afe)
 I also try the http://:8000 ,it just blank page and Open the new link repeatedly.

**Comment by ggilestro** [comment]
Ok, thanks for giving me feedback so promptly. Please try the following.
Stop and delete the current instance:
`sudo docker stop ethoscope-lab`
and 
`sudo docker rm ethoscope-lab`

Then start a new instance specifying the ip, as follows:

```
sudo docker run -d -p 8080:8080 \
      --name ethoscope-lab \
      --volume /ethoscope_data/results:/mnt/ethoscope_results:ro \
      --volume /home:/mnt/my_user_homes \
      --restart=unless-stopped \
      --ip 0.0.0.0 --port 8080 \
      ggilestro/ethoscope-lab
```

**Comment by FENGZHENGHFUT** [comment]
It displays an error
"unknown flag: --port"

**Comment by ggilestro** [comment]
Try without that flag then, just ip.
What operating system are you using?
And can you post the ouput of `docker version`

**Comment by FENGZHENGHFUT** [comment]
Thanks for your response,
    I had tried  just IP , it didn't work 
My OS is the image from your website:  manjaro-ethoscope-22.0.0-minimal-230127-linux54 
the docker version is 24.0.2

**Comment by FENGZHENGHFUT** [comment]
![IMG_20230720_170434](https://github.com/gilestrolab/ethoscopy/assets/139935090/7842160b-c814-4dd1-bed3-9ec2b1aa2c6d)

**Comment by antortjim** [comment]
For me it did not work either, but I checked [the Dockerfile](https://github.com/gilestrolab/ethoscopy/blob/main/docker/Dockerfile) and [the README](https://github.com/gilestrolab/ethoscopy/blob/main/docker/README.md) and it seems the exposed port is not 8080 , but 8000. So the correct command may be **not**

```
sudo docker run -d -p 8080:8080 \
      --name ethoscope-lab \
      --volume /ethoscope_data/results:/mnt/ethoscope_results:ro \
      --volume /home:/mnt/my_user_homes \
      --restart=unless-stopped \
      --ip 0.0.0.0 --port 8080 \
      ggilestro/ethoscope-lab
```

but 

```
sudo docker run -d -p 8000:8000 \
      --name ethoscope-lab \
      --volume /ethoscope_data/results:/mnt/ethoscope_results:ro \
      --volume /home:/mnt/my_user_homes \
      --restart=unless-stopped \
      --ip 0.0.0.0 --port 8000 \
      ggilestro/ethoscope-lab
```

This is the command I have run in my system

```
docker run -d -p 3333:8000 --name ethoscope-lab --volume /ethoscope_data/results:/mnt/ethoscope_results:ro --restart=unless-stopped ggilestro/ethoscope-lab
```

* I don't need sudo because I completed the docker installation step that allows me to skip sudo
* I use port 3333 just because 8000 is taken (could have picked anything)

Hope it helps :)
A

**Comment by FENGZHENGHFUT** [comment]
Thanks for your response
       I have changed to 8000 and opened the jupyter notebook successfully. 
      By the way, I have another nagging question. I burned the SD card and can use ethoscpe properly on a Raspberry Pi 3B , but the new SD card on a Raspberry Pi 3B+ doesn't work properly. The green light on the 3B+ blinks 4 times and then blinks 7 times fast. Can't connect to ethoscope-wifi either.
      Is this because the SD card's system is not compatible with the 3B+ or is it a power issue with the 3B+? The system burned on my SD card is 20201126_ethoscope_000.img.zip.  My power supply is 5V 2.4A.

**Comment by ggilestro** [comment]
Thanks a lot @antortjim for spotting they typo! I will change the instruction on the user manual.
@FENGZHENGHFUT the SD card image will definitely work on the 3B+ (this is what we are using on the lab and what we used to generate the image on the first place).
